services:
  db:
    image: mysql:oraclelinux9
    container_name: db
    ports:
      - "3000:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: apartment_building_manager_system
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  db_data:
