services:
  db:
    image: dhi.io/mysql:9.6
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: apartment_building_manager_system

volumes:
  db_data:
