apiVersion: v1
data:
  DB_HOST: database-statefulset-0.database-service.database.svc.cluster.local
kind: ConfigMap
metadata:
  name: backend-configmap
		labels:
    {{- include "abms.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-configmap
  namespace: backend
