apiVersion: v1
kind: Service
metadata:
  name: mail-service
	labels:
    {{- include "abms.labels" . | nindent 4 }}
    app.kubernetes.io/component: mail-service
spec:
  selector:
    	{{- include "abms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mail-pod
  ports:
    - protocol: TCP
      port: 1025
      targetPort: 1025
