apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  labels:
    {{- include "abms.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-config
data:
  MYSQL_ROOT_PASSWORD: "123456"
  MYSQL_DATABASE: "apartment_building_manager_system"