apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: database
  labels:
    {{- include "abms.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-service
spec:
  ports:
  - port: 3306
    name: database-service
  clusterIP: None
  selector:
    {{- include "abms.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database-pod