apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
  namespace: database
  labels:
    {{- include "abms.labels" . | nindent 4 }}
    app.kubernetes.io/component: database-statefulset
spec:
  selector:
    matchLabels:
      {{- include "abms.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database-pod
  serviceName: "database-service"
  minReadySeconds: 10
  template:
    metadata:
      labels:
        {{- include "abms.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database-pod
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8}}
      containers:
      - name: database
        image: {{ .Values.image.database.repository }}:{{ .Values.image.database.tag }}
        ports:
        - containerPort: 3306
          name: database-pod
        volumeMounts:
        - name: database-volume
          mountPath: /var/lib/mysql
        envFrom:
        - configMapRef:
            name: database-config
  volumeClaimTemplates:
  - metadata:
      name: database-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi


